### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by Nugation** [Amonith/mattermost-file-list#5]
Hey, 
I am using GitLab and integrated Mattermost. The activation of the plugin fails, because it can not locate the config.json file. 
I tried to put the file on following locations:
`/var/opt/mattermost/config.json`,`/opt/mattermost/config.json`, `/etc/mattermost/config.json` and `/mattermost/config.json`
But none of them works. 

Here is the error:
```
"Unable to activate plugin","plugin_id":"mattermost-file-list","error":"unable to start plugin: mattermost-file-list: failed to find config file config.json","errorVerbose":"failed to find config file config.json\nunable to start plugin: mattermost-file-list\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:230\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:95\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:172\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:82\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:59\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:245\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:191\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:144\ngithub.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/NYTimes/gziphandler/gzip.go:336\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}
```

I am pointless right now, maybe you can help me out?
Thanks

**Comment by Amonith** [comment]
Hi, are you using Mattermost on docker with alpine linux underneath (e.g. mattermost-docker images) by any chance?

**Comment by antt73** [comment]
I have the exact same error - using gitlab mattermost

**Comment by antt73** [comment]
Fixed - copied config.json to the plugin folder

**Comment by Amonith** [comment]
Interesting, this should not be required.
I will look into it this week.

**Comment by ArnY** [comment]
> I have the exact same error - using gitlab mattermost

Same here. Gitlab packages mattermost in its omnibus packages and stores the config.json file in /var/opt/gitlab/mattermost/

I don't know where @antt73 copied his/her config.json file but copying it in the plugin folder doesn't fix the problem here.

**Comment by PHCCorso** [comment]
@ArnY I figured it out: you must copy the `config.json` file to the `/var/opt/gitlab/mattermost/plugins/mattermost-file-list/server/dist` folder. Then it'll work.

**Comment by ArnY** [comment]
> @ArnY I figured it out: you must copy the `config.json` file to the `/var/opt/gitlab/mattermost/plugins/mattermost-file-list/server/dist` folder. Then it'll work.

Indeed! and chown it to mattermost:mattermost...

**Comment by Amonith** [comment]
This error will be solved in the upcoming release, but unfortunately I will have to bump the min version of MM to 5.15. The MM team introduced an API endpoint thanks to which I won't have to read config.json directly.

**Comment by Amonith** [comment]
Hi @Nugation, @ArnY, @PHCCorso , @antt73,
Please check out the latest release 0.6.0:
https://github.com/Amonith/mattermost-file-list/releases/tag/v0.6.0

It now uses new official API for reading the config introduced in MM v5.16 and that should permamently fix the issue.
Feel free to reopen the issue if it still doesn't work.
